import 'assets/styles/globals.css'

import type { Metadata } from 'next'
import { Courier_Prime } from 'next/font/google'
import Providers from 'contexts/providers'

const courier = Courier_Prime({
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: 'arod.studio react ts template',
  description: 'Generated by create next app and customized by arod.studio',
}

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={courier.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}

export default RootLayout
